[versions]
agp = "8.2.2"
androidx-appcompat = "1.6.1"
androidx-cardview = "1.0.0"
androidx-compose = "1.4.3"
androidx-compose-compiler = "1.5.10"
androidx-test-junit = "1.1.5"
androidx-test-rules = "1.5.0"
dokka = "1.9.10"
espresso = "3.5.1"
kotlin = "1.9.22"
ktlint = "12.1.0"
material = "1.11.0"
publishPlugin = "1.3.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules"}